### ISSUE TITLE
Libraries version

### ISSUE THREAD

**Issue by truhoang** [mcgill-robotics/ros-leddar#2]
Hello, 

I rand into the incompatibility issue with the libraries file in `/lib`. Do you know the chip architecture these library files were built for (i.e.  x86_64 (64-bit) or x86 (32-bit))?

Thanks

**Comment by anassinator** [comment]
They target `x86_64`, so you can replace them with the ones of your relevant target form LeddarTech's support website and it should work.

**Comment by truhoang** [comment]
Do you know the specific version you used? I download the latest version and the Leddar functions (in LeddarC.h) are different than the one you use in leddar.cpp

**Comment by anassinator** [comment]
We used v2.10.x which might not be available on their website anymore. If there are any changes to be made to support v3.x, I would gladly welcome a PR. It's something I've been meaning to do, but I'm too busy for right now. We can also have the `lib` and `include` folders not be bundled in so as to not require a specific target.

**Comment by truhoang** [comment]
Can you add me as a contributor? I created a new leddar.cpp and updated the library files and would like to push to this rep

**Comment by anassinator** [comment]
Actually, can you just fork it and create the PR?

**Comment by truhoang** [comment]
Submitted the PR
