### ISSUE TITLE
Syntax error with make file? 

### ISSUE THREAD

**Issue by yunfei96** [mcgill-robotics/ros-leddar#5]
Here is what i got when i try to compile it. 
I think it means "-l LeddarTeck". Any idea where I can modify the make file to solve that problem? 
[odroid C2]
[LeddarSDK3.2.0_arm]
//-----------------------------------------------------------------------------------------------------------------------------------------
[ 33%] Built target leddar_gencfg
[ 66%] Linking CXX executable /home/odroid/catkin_ws/devel/lib/leddar/leddar
/usr/bin/ld: skipping incompatible /home/odroid/LeddarSDK3.2.0_arm/Release/libLeddarTech.so when searching for -lLeddarTech
/usr/bin/ld: cannot find -lLeddarTech
/usr/bin/ld: skipping incompatible /home/odroid/LeddarSDK3.2.0_arm/Release/libLeddar.so when searching for -lLeddar
/usr/bin/ld: cannot find -lLeddar
/usr/bin/ld: skipping incompatible /home/odroid/LeddarSDK3.2.0_arm/Release/libLeddarC.so when searching for -lLeddarC
/usr/bin/ld: cannot find -lLeddarC
collect2: error: ld returned 1 exit status
leddar/CMakeFiles/leddar.dir/build.make:114: recipe for target '/home/odroid/catkin_ws/devel/lib/leddar/leddar' failed
make[2]: *** [/home/odroid/catkin_ws/devel/lib/leddar/leddar] Error 1
CMakeFiles/Makefile2:538: recipe for target 'leddar/CMakeFiles/leddar.dir/all' failed
make[1]: *** [leddar/CMakeFiles/leddar.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by anassinator** [comment]
Did you follow the instructions in the README? And are you able to reproduce on x86/64 instead of ARM?

**Comment by yunfei96** [comment]
Thanks for your reply. I found the problem. It caused by the 64bit arm cpu. Leddar Tech only support 32bit arm cpu.
