### ISSUE TITLE
Code does not compile

### ISSUE THREAD

**Issue by ChrisGermany** [mcgill-robotics/ros-leddar#6]
Hi I am trying to compile your code. I followed the steps in the README and use SDK 3.2. It would be nice if you could help me. I get the following error

**/usr/bin/ld:`warning: libQt5SerialPort.so.5, needed by /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libLeddar.so, not found (try using -rpath or -rpath-link)
CMakeFiles/leddar.dir/src/leddar.cpp.o: In function `stream(void*)':
leddar.cpp:(.text+0x120c): undefined reference to `LeddarAddCallback'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libLeddarTech.so: undefined reference to `QSerialPort::setStopBits(QSerialPort::StopBits)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libLeddarTech.so: undefined reference to `QSerialPort::~QSerialPort()'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libLeddar.so: undefined reference to `QSerialPortInfo::~QSerialPortInfo()'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libLeddarTech.so: undefined reference to `QSerialPort::setDataBits(QSerialPort::DataBits)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libLeddarTech.so: undefined reference to `QSerialPort::QSerialPort(QObject*)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libLeddarTech.so: undefined reference to `QSerialPort::close()'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libLeddarTech.so: undefined reference to `QSerialPort::setPortName(QString const&)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libLeddar.so: undefined reference to `QSerialPortInfo::portName() const'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libLeddarTech.so: undefined reference to `QSerialPort::error() const'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libLeddarTech.so: undefined reference to `QSerialPort::flush()'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libLeddarTech.so: undefined reference to `QSerialPort::setParity(QSerialPort::Parity)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libLeddarTech.so: undefined reference to `QSerialPort::waitForReadyRead(int)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libLeddar.so: undefined reference to `QSerialPortInfo::description() const'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libLeddarTech.so: undefined reference to `QSerialPort::open(QFlags<QIODevice::OpenModeFlag>)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libLeddar.so: undefined reference to `QSerialPortInfo::QSerialPortInfo(QSerialPortInfo const&)'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libLeddar.so: undefined reference to `QSerialPortInfo::availablePorts()'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libLeddarTech.so: undefined reference to `QSerialPort::setBaudRate(int, QFlags<QSerialPort::Direction>)'
collect2: error: ld returned 1 exit status
leddar/CMakeFiles/leddar.dir/build.make:114: recipe for target '/home/lhr/catkin_ws/devel/lib/leddar/leddar' failed
make[2]: *** [/home/lhr/catkin_ws/devel/lib/leddar/leddar] Error 1
CMakeFiles/Makefile2:2286: recipe for target 'leddar/CMakeFiles/leddar.dir/all' failed
make[1]: *** [leddar/CMakeFiles/leddar.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error **

**Comment by anassinator** [comment]
@ChrisGermany 
Unfortunately the code was never updated to run on v3.2 and currently only supports v2.x (IIRC). #3 was meant to fix that, but it seems to be abandoned.

Since I don't currently have the time to fix this, you can either try to take over the work in #3 or simply revert to 5994c131 where the older SDK is already bundled.

**Comment by ChrisGermany** [comment]
Ok so I tried to get it working and it compiles, the only problem I am having is that it does not enter my callback function. Could I post my code and you would take a look at it and probably tell me whats wrong?

**Comment by anassinator** [comment]
Sure, I can try, but I won't be able to test it as I don't have the hardware right now.

Did you try reverting to the commit I mentioned BTW? Because that should work.

**Comment by ChrisGermany** [comment]
I actually got it working. Thanks for your help. The code is a lot different, since I followed their SDK and kind of merged it with yours. Do you still want me to share it with you?

**Comment by anassinator** [comment]
Yeah, you can also open a PR

**Comment by anassinator** [comment]
This should be fixed now

**Comment by veervishu99** [comment]
can you tell me how did you solve this error I am also getting the same error?
