### ISSUE TITLE
can't set PID_LED_INTENSITY: access denied

### ISSUE THREAD

**Issue by calocedrus** [mcgill-robotics/ros-leddar#9]
Hi,
I am attempting at using a MOD-36-10 leddar sensor module (part number 75B0010) in ROS.
I can compile your ros package fine, can launch it but I get the following error:
[ERROR] [1523518236.536246578]: LeddarSetProperty(PID_LED_INTENSITY): LD_ACCESS_DENIED
Reading your github information, I investigated the possibility that the udev rules were incorrect, but running lsusb -vvv shows the idVendor, idProduct and manufacturer are all correct. 

The messages I get when are the following, after launching the package according to your instructions:
```
... logging to /home/j300ros/.ros/log/ed44ead0-3e21-11e8-aae6-3497f68038a7/roslaunch-j300-ros-3312.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.
started roslaunch server http://j300-ros:44911/

SUMMARY
========
PARAMETERS
 * /leddar/fov: 36
 * /leddar/frame: leddar
 * /leddar/range: 12
 * /leddar/serial: AG51009
 * /leddar/type: USB
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
NODES
  /
    leddar (leddar/leddar)
ROS_MASTER_URI=http://localhost:11311
process[leddar-1]: started with pid [3329]
[ INFO] [1523518236.530058223]: Connected to AG51009
[ INFO] [1523518236.536201468]: Reconfiguring...
[ERROR] [1523518236.536246578]: LeddarSetProperty(PID_LED_INTENSITY): LD_ACCESS_DENIED
[ INFO] [1523518236.580804510]: Streaming...

```
If I launch rviz, I see nothing even after having added laserscan (the scan data) to rviz.

I've also tried to change the LED_INTENSITY in the Scan.cfg but to no avail. If I use the on-the-fly reconfigure, any time I change the led intensity I see the error message LeddarSetProperty(PID_LED_INTENSITY): LD_ACCESS_DENIED.

This is my very first attempt at using a LIDAR  (and the 1st time using a LIDAR in ROS), at this point I would like to ask for help! What can be the origin of the LD_ACCESS_DENIED error?

**Comment by anassinator** [comment]
Seems like you did everything fine and got it working. That just means that setting is not configurable on your sensor, so it will stick to whatever they decided should be the default regardless of what you set in dynamic reconfigure. That error comes from the SDK directly, so there’s nothing we can do about it. If you absolutely want to change the intensity, you would need to ask LeddarTech support. There’s nothinng wrong with your udev rules.

As for rviz, did you make sure to set what frame you want to visualize with respect to? Nothing will show up until you select an option.

**Comment by calocedrus** [comment]
You are right, the sensor was fine and it was my settings in rviz: I hadn't set a reference frame and had to select the appropriate topic (it was the 1st time I use rviz). Now I have data showing up in rviz. 
I will see with LeddarTech support how to set the LED intensity.
Thanks!

**Comment by anassinator** [comment]
No problem!
